version: '3'

services:
  mongo_dev:
    container_name: new_numerology_mongo_dev
    image: mongo:6.0
    restart: always
    ports:
      - ${MONGO_EXPOSED_PORT}:${MONGODB_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - ./volumes/data/mongo:/data/db
    networks:
      - new_numerology_backend_network

  redis_dev:
    container_name: new_numerology_redis_dev
    image: redis:6.2-alpine
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_AUTH_PASSWORD}
    restart: always
    ports:
      - ${REDIS_EXPOSED_PORT}:${REDIS_PORT}
    volumes:
      - ./volumes/data/redis:/data
    networks:
      - new_numerology_backend_network

  new_numerology_api_dev:
    container_name: new_numerology_api_dev
    image: new_numerology_api_dev:latest
    build:
      context: .
      target: builder
    environment:
      TERM: linux
      LANG: "C.UTF-8"
      NODE_ENV: development
    env_file:
      - .env.api.docker.local
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "2"
    restart: "always"
    ports:
      - ${SERVER_EXPOSED_PORT}:${SERVER_PORT}
    depends_on:
      - mongo_dev
      - redis_dev
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
    networks:
      - new_numerology_backend_network

networks:
  new_numerology_backend_network:
    driver: bridge
